import * as T from './three.module.js';
const $=id=>document.getElementById(id),N=19,S=2.7,keys={},joy={x:0,z:0};
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true});}catch(e){$('error').hidden=false;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0x100e09);
const scene=new T.Scene();scene.fog=new T.FogExp2(0x151209,.065);const camera=new T.PerspectiveCamera(78,1,.08,100);
scene.add(new T.HemisphereLight(0xa8b79c,0x161006,.85));const sun=new T.DirectionalLight(0xefbd71,1.0);sun.position.set(12,28,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35});sun.shadow.bias=-.001;scene.add(sun);
const hunterLight=new T.PointLight(0xffd590,13,15,1.5);scene.add(hunterLight);
let board=new T.Group();scene.add(board);let grid=[],npcs=[],cheeses=[],rat,gate,elapsed=0,caught=0,escaped=0,collected=0,mode='intro',sniffCD=0,sniffFor=0,dashCD=0,dashFor=0,toastFor=0,walkTime=0,soundOn=true,audio;
let mapFor=0,mapCD=0;
const MAP_DURATION=10,MAP_COOLDOWN=20;
let yaw=0,pitch=0,lookPointer=null,lastLook={x:0,y:0},endingTime=0,won=false;
const exits=[{x:17,z:17,name:'Sur',color:0xed9460},{x:1,z:1,name:'Norte',color:0x92c2ba}],start={x:9,z:9};let gates=[],tunnels=[],travel=null,tunnelCooldown=0;
const tunnelPairs=[[[9,9],[1,15]],[[1,5],[17,13]],[[5,17],[13,1]]];
// 2 s sprint + 2.5 s walk + capture reach + one tile of corner tolerance.
const CAMP_RADIUS=Math.ceil(7.7*2+4.5*(4.5-2)+1.05+S),CAMP_WARN=7,CAMP_LIMIT=12;
let campScan=0,ratDistances=new Map();
function material(color){return new T.MeshStandardMaterial({color,roughness:.85});}const mats={wall:material(0xffffff),floor:material(0x665020),rat:material(0x869995),ear:material(0xe5a5a1),nose:material(0xf29b9e),dark:material(0x10231b),cheese:material(0xffd34a)};
// Seamless procedural cheese texture: shaded elliptical pores, stored entirely locally.
const texSize=256,pixels=new Uint8Array(texSize*texSize*4),pores=[[.2,.24,.095,.065],[.72,.17,.08,.12],[.49,.55,.11,.08],[.83,.76,.10,.065],[.14,.8,.05,.09]];
for(let y=0;y<texSize;y++)for(let x=0;x<texSize;x++){let shade=1;for(let [cx,cy,rx,ry] of pores){let dx=(x/texSize-cx)/rx,dy=(y/texSize-cy)/ry,r=Math.hypot(dx,dy);if(r<1){shade=Math.min(shade,.43+.29*r+.12*dy);}else if(r<1.10)shade=1.09;}let grain=1+.013*Math.sin(x*17.1+y*7.3),i=(y*texSize+x)*4;pixels[i]=Math.min(255,246*shade*grain);pixels[i+1]=Math.min(255,188*shade*grain);pixels[i+2]=Math.min(255,52*shade*grain);pixels[i+3]=255;}
const cheeseTexture=new T.DataTexture(pixels,texSize,texSize);cheeseTexture.colorSpace=T.SRGBColorSpace;cheeseTexture.magFilter=T.LinearFilter;cheeseTexture.minFilter=T.LinearMipmapLinearFilter;cheeseTexture.generateMipmaps=true;cheeseTexture.needsUpdate=true;mats.wall.map=cheeseTexture;
function mesh(geo,mat,parent,x=0,y=0,z=0){let m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(parent,mat,x,y,z,sx,sy,sz){let m=mesh(new T.SphereGeometry(1,12,9),mat,parent,x,y,z);m.scale.set(sx,sy,sz);return m;}
// Stylized sculpted characters, built as articulated meshes rather than block avatars.
function stroke(parent,points,color=0xc2b18c){const line=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color}));parent.add(line);return line;}
function makeRat(){const g=new T.Group(),fur=material(0x514b41),tuft=material(0x38382e),muzzle=material(0x948572),skin=material(0xad7770),ivory=material(0xe1c994),black=material(0x100e0a),eyeMat=new T.MeshStandardMaterial({color:0xf3bb51,emissive:0xb45a13,emissiveIntensity:.7,roughness:.24});
sphere(g,fur,0,.63,.1,.62,.56,.88);sphere(g,muzzle,0,.42,-.52,.42,.32,.37);
const head=new T.Group();head.position.set(0,.77,-.60);g.add(head);g.head=head;sphere(head,fur,0,.02,0,.47,.4,.5);sphere(head,muzzle,-.15,-.12,-.38,.24,.2,.27);sphere(head,muzzle,.15,-.12,-.38,.24,.2,.27);sphere(head,skin,0,-.02,-.64,.16,.105,.1);
g.ears=[];g.paws=[];for(let sign of [-1,1]){const ear=new T.Group();ear.position.set(sign*.37,.37,.04);head.add(ear);sphere(ear,fur,0,0,0,.27,.32,.095);sphere(ear,skin,0,0,-.073,.205,.235,.027);ear.rotation.z=-sign*.25;g.ears.push(ear);
sphere(head,black,sign*.29,.14,-.34,.155,.15,.10);sphere(head,eyeMat,sign*.29,.14,-.413,.107,.108,.052);sphere(head,black,sign*.29,.14,-.455,.032,.084,.019);sphere(head,ivory,sign*.26,.17,-.471,.018,.022,.012);
let brow=mesh(new T.CapsuleGeometry(.045,.21,3,7),fur,head,sign*.30,.285,-.39);brow.rotation.z=sign*1.23;
let tooth=mesh(new T.BoxGeometry(.115,.19,.075),ivory,head,sign*.069,-.32,-.50);tooth.rotation.x=-.18;
let paw=new T.Group();paw.position.set(sign*.43,.20,-.39);g.add(paw);sphere(paw,skin,0,0,0,.17,.12,.23);for(let j=0;j<3;j++){let claw=mesh(new T.ConeGeometry(.035,.15,6),ivory,paw,(j-1)*.085,-.01,-.23);claw.rotation.x=-Math.PI/2;}g.paws.push(paw);sphere(g,skin,sign*.46,.17,.63,.20,.13,.30);
for(let k=0;k<4;k++)stroke(head,[[sign*.14,-.11,-.57],[sign*.49,-.07+k*.055,-.52],[sign*(.82+k*.025),-.15+k*.10,-.42+k*.08]],0xb6ac96);
for(let k=0;k<7;k++){const q=mesh(new T.ConeGeometry(.085,.26,5),tuft,g,sign*(.48+.07*Math.sin(k)),.64+.16*Math.sin(k*2),-.1+k*.13);q.rotation.z=-sign*1.1;}}
for(let k=0;k<10;k++){const q=mesh(new T.ConeGeometry(.10,.27,5),tuft,g,.13*Math.sin(k*4),1.02+.04*Math.cos(k),-.22+k*.10);q.rotation.x=.5;}
// A ragged ear and a stitched scar distinguish this rat from a smooth toy.
sphere(g.ears[1],black,.14,.19,-.083,.072,.087,.03);stroke(head,[[.08,.34,-.32],[.14,.23,-.43],[.17,.03,-.48]],0xbf9690);for(let k=0;k<4;k++)stroke(head,[[.09+k*.018,.29-k*.065,-.42],[.18+k*.009,.32-k*.065,-.44]],0x392b26);
const tailPath=new T.CatmullRomCurve3([new T.Vector3(0,.33,.78),new T.Vector3(.24,.18,1.23),new T.Vector3(.85,.12,1.66),new T.Vector3(1.14,.18,1.28)]);mesh(new T.TubeGeometry(tailPath,22,.07,8,false),skin,g);for(let k=1;k<14;k++){let point=tailPath.getPoint(k/15),ring=mesh(new T.TorusGeometry(.071,.011,4,9),material(0x74504b),g,...point.toArray());ring.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),tailPath.getTangent(k/15).normalize());}
return g;}
function makeHuman(color,index=0){const g=new T.Group(),coat=material(color),pants=material(0x33352d),leather=material(0x403125),skin=material([0xc29c7e,0xad7d5d,0xd4b295,0x9b7257,0xc79d78][index]),hair=material([0x3c3026,0x251f1a,0x70513a,0x3b3630,0x8d7557][index]),trim=material(0xa59874),black=material(0x17140f),eye=material(0xd8d5ba);
sphere(g,coat,0,.90,0,.32,.43,.225);mesh(new T.CylinderGeometry(.29,.35,.35,9),coat,g,0,.65,0);mesh(new T.CylinderGeometry(.30,.30,.07,10),leather,g,0,.68,0);mesh(new T.BoxGeometry(.09,.07,.025),trim,g,0,.68,-.30);
for(let sign of [-1,1]){let lapel=mesh(new T.BoxGeometry(.10,.24,.035),trim,g,sign*.11,1.15,-.19);lapel.rotation.z=sign*.3;mesh(new T.BoxGeometry(.135,.15,.055),leather,g,sign*.19,.87,-.21);for(let j=0;j<3;j++)stroke(g,[[sign*.24,.92-j*.04,-.245],[sign*.15,.92-j*.04,-.245]],0x807255);}
for(let k=0;k<4;k++)sphere(g,trim,0,1.06-k*.105,-.227,.025,.025,.016);
const head=new T.Group();head.position.set(0,1.43,0);g.add(head);g.head=head;sphere(head,skin,0,0,0,.245,.29,.225);sphere(head,skin,0,-.015,-.237,.06,.085,.072);for(let sign of [-1,1]){sphere(head,skin,sign*.24,-.02,0,.05,.09,.055);sphere(head,black,sign*.09,.055,-.197,.071,.075,.033);sphere(head,eye,sign*.09,.06,-.22,.049,.052,.015);sphere(head,black,sign*.09,.06,-.235,.02,.035,.008);let brow=mesh(new T.BoxGeometry(.13,.03,.03),hair,head,sign*.10,.145,-.19);brow.rotation.z=sign*-.25;}sphere(head,black,0,-.15,-.188,.054,.069,.024);
sphere(head,hair,0,.19,.03,.25,.12,.205);for(let k=0;k<4;k++)sphere(head,hair,-.16+k*.1,.23,-.11,.095,.065,.095);
// Miner cap, lamp, backpack, straps and boots tie the intruders to the cellar.
mesh(new T.CylinderGeometry(.26,.27,.14,12),leather,head,0,.29,.01);mesh(new T.BoxGeometry(.44,.035,.25),leather,head,0,.23,-.14);const lamp=new T.MeshStandardMaterial({color:0xffdc8e,emissive:0xf5b951,emissiveIntensity:1.3});let housing=mesh(new T.CylinderGeometry(.095,.095,.07,10),black,head,0,.29,-.26);housing.rotation.x=Math.PI/2;sphere(head,lamp,0,.29,-.305,.065,.065,.017);
sphere(g,leather,0,.93,.27,.29,.33,.17);mesh(new T.BoxGeometry(.34,.06,.045),trim,g,0,1.02,.43);for(let sign of [-1,1]){mesh(new T.BoxGeometry(.045,.56,.04),leather,g,sign*.25,.99,-.16);}
g.legs=[];g.arms=[];for(let sign of [-1,1]){const leg=new T.Group();leg.position.set(sign*.155,.61,0);g.add(leg);mesh(new T.CapsuleGeometry(.105,.27,3,8),pants,leg,0,-.24,0);sphere(leg,leather,0,-.50,-.06,.14,.13,.24);mesh(new T.BoxGeometry(.26,.045,.38),black,leg,0,-.595,-.06);g.legs.push(leg);
const arm=new T.Group();arm.position.set(sign*.33,1.13,0);g.add(arm);mesh(new T.CapsuleGeometry(.092,.30,3,8),coat,arm,sign*.03,-.20,0);sphere(arm,leather,sign*.03,-.46,-.015,.093,.11,.10);g.arms.push(arm);}
return g;}
const dirs=[[1,0],[-1,0],[0,1],[0,-1]],cell=(x,z)=>grid[z]?.[x]===0,key=(x,z)=>z*N+x,world=n=>(n-(N-1)/2)*S,tile=n=>Math.round(n/S+(N-1)/2);
function generate(){grid=Array.from({length:N},()=>Array(N).fill(1));const stack=[[1,1]];grid[1][1]=0;while(stack.length){let [x,z]=stack.at(-1);let options=dirs.map(([a,b])=>[x+a*2,z+b*2]).filter(([a,b])=>a>0&&b>0&&a<N-1&&b<N-1&&grid[b][a]);if(!options.length){stack.pop();continue;}let [a,b]=options[Math.floor(Math.random()*options.length)];grid[(z+b)/2][(x+a)/2]=0;grid[b][a]=0;stack.push([a,b]);}for(let i=0;i<37;i++){let x=1+Math.floor(Math.random()*(N-2)),z=1+Math.floor(Math.random()*(N-2));if(grid[z][x]&&((cell(x-1,z)&&cell(x+1,z))||(cell(x,z-1)&&cell(x,z+1))))grid[z][x]=0;}}
function path(from,to){let queue=[from],seen=new Map([[key(from.x,from.z),null]]);for(let i=0;i<queue.length;i++){let p=queue[i];if(p.x===to.x&&p.z===to.z){let out=[];while(p){out.unshift(p);p=seen.get(key(p.x,p.z));}return out.slice(1);}for(let [dx,dz]of dirs){let x=p.x+dx,z=p.z+dz,k=key(x,z);if(cell(x,z)&&!seen.has(k)){seen.set(k,p);queue.push({x,z});}}}return [];}
function message(t){$('toast').textContent=t;toastFor=3;$('toast').style.opacity=1;}
function beep(freq=440,duration=.1){if(!soundOn||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+duration);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration);}
function reset(){board.traverse(o=>{if(o.geometry)o.geometry.dispose();});scene.remove(board);board=new T.Group();scene.add(board);generate();npcs=[];cheeses=[];gates=[];tunnels=[];travel=null;tunnelCooldown=0;campScan=0;ratDistances=new Map();elapsed=0;caught=escaped=collected=0;sniffCD=sniffFor=dashCD=dashFor=mapFor=mapCD=0;
mesh(new T.BoxGeometry(N*S, .35,N*S),mats.floor,board,0,-.2,0);const box=new T.BoxGeometry(S,3.8,S);let count=grid.flat().filter(Boolean).length,inst=new T.InstancedMesh(box,mats.wall,count),dummy=new T.Object3D(),i=0;for(let z=0;z<N;z++)for(let x=0;x<N;x++)if(grid[z][x]){dummy.position.set(world(x),1.9,world(z));dummy.updateMatrix();inst.setMatrixAt(i++,dummy.matrix);}inst.castShadow=true;inst.receiveShadow=true;board.add(inst);
// Tile seams make the narrow passages readable without additional textures.
const floorLines=new T.GridHelper(N*S,N,0x435640,0x334b3a);floorLines.position.y=.006;board.add(floorLines);
for(const exit of exits){gate=new T.Group();gate.position.set(world(exit.x),0,world(exit.z));const gateMat=material(exit.color);for(let x of [-.9,.9])mesh(new T.BoxGeometry(.15,2.4,.2),gateMat,gate,x,1.2,0);mesh(new T.BoxGeometry(1.95,.2,.2),gateMat,gate,0,2.4,0);gate.bars=[];for(let x=-.6;x<=.6;x+=.3)gate.bars.push(mesh(new T.BoxGeometry(.07,2,.1),gateMat,gate,x,1.1,0));board.add(gate);gates.push(gate);}
for(let pair=0;pair<tunnelPairs.length;pair++)for(let side=0;side<2;side++){let [x,z]=tunnelPairs[pair][side],[tx,tz]=tunnelPairs[pair][1-side];let dir=dirs.find(([dx,dz])=>!cell(x+dx,z+dz))||[0,-1];let hole=new T.Group();hole.position.set(world(x)+dir[0]*1.25,.65,world(z)+dir[1]*1.25);hole.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(-dir[0],0,-dir[1]));mesh(new T.CircleGeometry(.72,20),material(0x030403),hole,0,0,0);mesh(new T.TorusGeometry(.76,.12,7,20),material(0x485a48),hole,0,0,.05);const edge=new T.MeshStandardMaterial({color:0x9aac77,emissive:0x506534,emissiveIntensity:.7});for(let k=0;k<3;k++)mesh(new T.BoxGeometry(.06,.24,.05),edge,hole,-.20+k*.20,.92,.05);board.add(hole);tunnels.push({x,z,tx,tz,pair,dir,hole});}
rat=makeRat();rat.position.set(world(start.x),0,world(start.z));board.add(rat);rat.visible=false;
const spawns=[[1,1],[17,1],[1,17],[17,13],[7,1]],colors=[0x875442,0x52656a,0x69604b,0x8b7649,0x506151];spawns.forEach(([x,z],i)=>{let model=makeHuman(colors[i],i);model.position.set(world(x),0,world(z));board.add(model);npcs.push({model,x,z,path:[],wait:1+i*.3,state:'active',targetCheese:null,think:0,flee:false,color:colors[i]});});
const spaces=[];for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(cell(x,z)&&Math.abs(x-start.x)+Math.abs(z-start.z)>3&&!exits.some(e=>e.x===x&&e.z===z)&&!tunnels.some(t=>t.x===x&&t.z===z)&&!spawns.some(([a,b])=>a===x&&b===z))spaces.push({x,z});
for(let i=0;i<8;i++){spaces.sort((a,b)=>{const score=c=>Math.min(...[start,...cheeses].map(q=>Math.abs(q.x-c.x)+Math.abs(q.z-c.z)))+ (dirs.filter(([dx,dz])=>cell(c.x+dx,c.z+dz)).length===1?4:0);return score(b)-score(a);});let c=spaces.splice(Math.floor(Math.random()*Math.min(4,spaces.length)),1)[0],g=new T.Group();const piece=mesh(new T.CylinderGeometry(.35,.46,.35,3),mats.cheese,g,0,.34,0);const cage=new T.Group();g.add(cage);let iron=material(0x514434);mesh(new T.BoxGeometry(1.08,.12,1.08),iron,cage,0,.06,0);mesh(new T.BoxGeometry(1.08,.09,1.08),iron,cage,0,.87,0);for(let sign of [-1,1])for(let j=-1;j<=1;j++){mesh(new T.BoxGeometry(.045,.8,.045),iron,cage,j*.43,.44,sign*.48);mesh(new T.BoxGeometry(.045,.8,.045),iron,cage,sign*.48,.44,j*.43);}mesh(new T.BoxGeometry(.2,.24,.12),material(0xba8c3a),cage,0,.43,-.54);const progress=mesh(new T.BoxGeometry(.95,.05,.035),material(0xe8bf64),g,0,1.03,0);progress.visible=false;g.position.set(world(c.x),0,world(c.z));board.add(g);cheeses.push({...c,model:g,piece,cage,progress,work:0,required:4.5,taken:false,camp:0,relocating:null,grace:0});}
yaw=0;pitch=0;const openDirection=dirs.find(([x,z])=>cell(start.x+x,start.z+z));if(openDirection)yaw=Math.atan2(-openDirection[0],-openDirection[1]);camera.position.set(rat.position.x,.82,rat.position.z);camera.rotation.order='YXZ';camera.rotation.set(0,yaw,0);hud();}
function begin(){if(!audio){try{audio=new (window.AudioContext||window.webkitAudioContext)();}catch{}}audio?.resume();reset();$('ending').hidden=true;$('campWarning').hidden=true;document.body.classList.remove('ended');mode='playing';$('overlay').hidden=true;$('pauseOverlay').hidden=true;lockMouse();message('E: olfato · Ratón: mirar · WASD: moverte');}
function hud(){$('caught').innerHTML=caught+' <i>/ 5</i>';$('escaped').textContent=escaped+' escaparon';let t=Math.max(0,Math.ceil(300-elapsed));$('time').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('goal').textContent=collected<8?`2 salidas cerradas · ${collected}/8 quesos`:'¡Dos salidas abiertas: Norte y Sur!';$('sniffText').textContent=sniffCD>0?`Listo en ${Math.ceil(sniffCD)} s`:'Revela a los exploradores';$('dashText').textContent=dashCD>0?`Listo en ${Math.ceil(dashCD)} s`:'Corre durante 2 segundos';$('sniff').disabled=sniffCD>0;$('dash').disabled=dashCD>0;$('sniffBar').style.width=(100*(1-sniffCD/14))+'%';$('dashBar').style.width=(100*(1-dashCD/8))+'%';$('sniff').classList.toggle('active',sniffFor>0);$('dash').classList.toggle('active',dashFor>0);$('time').classList.toggle('urgent',t<60);$('preyMarks').innerHTML=Array.from({length:5},(_,i)=>'<span class="'+(i<caught?'marked':'')+'">╱</span>').join('');}
function ability(name){if(mode!=='playing')return;if(name==='map'&&mapCD<=0){mapFor=MAP_DURATION;mapCD=MAP_COOLDOWN;message('Instinto activo: oriéntate con el mapa durante 10 segundos.');beep(380,.2);}if(name==='sniff'&&sniffCD<=0){sniffCD=14;sniffFor=5;message('Olfato activo: rastros visibles durante 5 segundos');beep(700,.2);}if(name==='dash'&&dashCD<=0){dashCD=8;dashFor=2;beep(240,.2);}}
function pause(){if(mode==='playing'){mode='paused';$('pauseOverlay').hidden=false;document.exitPointerLock?.();}else if(mode==='paused'){mode='playing';$('pauseOverlay').hidden=true;lockMouse();}Object.keys(keys).forEach(k=>keys[k]=false);joy.x=joy.z=0;}
function finish(){mode='ended';won=caught===5;endingTime=0;document.exitPointerLock?.();$('overlay').hidden=true;$('ending').hidden=false;document.body.classList.add('ended');$('endingEyebrow').textContent=won?'VICTORIA · LA MADRIGUERA ESTÁ A SALVO':'DERROTA · SE LLEVARON TU QUESO';$('endingTitle').innerHTML=won?'Nadie sale.<br><em>Tú mandas.</em>':'Esta noche,<br><em>ganaron ellos.</em>';$('endingDescription').textContent=won?'Cinco intrusos. Cinco capturas. Tu rata se ha ganado un festín.':'La rata baja las orejas. El laberinto se ha quedado demasiado silencioso.';$('endingStats').textContent=`${caught}/5 atrapados · ${escaped} escaparon · ${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;trophy.visible=won;tears.forEach(t=>t.visible=!won);beep(won?880:220,.5);}
function clearPosition(x,z){for(let dx of [-.37,.37])for(let dz of [-.37,.37])if(!cell(tile(x+dx),tile(z+dz)))return false;return true;}
function update(dt){mapFor=Math.max(0,mapFor-dt);mapCD=Math.max(0,mapCD-dt);updateTunnel(dt);elapsed+=dt;walkTime+=dt;sniffCD=Math.max(0,sniffCD-dt);dashCD=Math.max(0,dashCD-dt);sniffFor=Math.max(0,sniffFor-dt);dashFor=Math.max(0,dashFor-dt);if(keys.arrowleft)yaw+=dt*1.9;if(keys.arrowright)yaw-=dt*1.9;const side=(keys.d?1:0)-(keys.a?1:0)+joy.x,forward=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.z;let dx=side*Math.cos(yaw)-forward*Math.sin(yaw),dz=-side*Math.sin(yaw)-forward*Math.cos(yaw);if(travel){dx=0;dz=0;}const len=Math.hypot(dx,dz);if(len>.1){dx/=Math.max(1,len);dz/=Math.max(1,len);const v=(dashFor>0?7.7:4.5)*dt;let p=rat.position;if(clearPosition(p.x+dx*v,p.z))p.x+=dx*v;if(clearPosition(p.x,p.z+dz*v))p.z+=dz*v;rat.rotation.y=Math.atan2(-dx,-dz);rat.position.y=Math.sin(walkTime*22)*.04;}else rat.position.y=0;
updateCamping(dt);for(let c of cheeses)if(!c.taken){c.piece.rotation.y+=dt;c._working=false;}
for(let n of npcs){if(n.state!=='active'){releaseCheese(n);continue;}if(n.targetCheese&&(n.targetCheese.taken||n.targetCheese.relocating))releaseCheese(n);let p=n.model.position,dist=p.distanceTo(rat.position);if(!travel&&dist<1.05&&lineClear(p,rat.position)){n.state='caught';releaseCheese(n);caught++;n.model.visible=false;message(`¡Atrapado! ${caught} de 5`);beep(520,.15);continue;}senseRat(n,dt);n.wait-=dt;if(n.wait>0&&!n.flee)continue;
if(!n.path.length){let from={x:tile(p.x),z:tile(p.z)},target;if(n.flee){n.path=fleeRoute(from,n);}else if(collected>=8){n.path=escapeRoute(from).slice(0,1);}else{n.path=cheeseRoute(n,from);}}
if(n.path.length){let dest=n.path[0],vx=world(dest.x)-p.x,vz=world(dest.z)-p.z,d=Math.hypot(vx,vz),step=(n.flee?3.05:2.3)*dt;if(d<=step){p.x=world(dest.x);p.z=world(dest.z);n.path.shift();if(n.flee)n.path=[];}else{p.x+=vx/d*step;p.z+=vz/d*step;n.model.rotation.y=Math.atan2(-vx,-vz);}n.model.legs.forEach((leg,i)=>leg.rotation.x=Math.sin(walkTime*13+i*Math.PI)*.5);n.model.arms.forEach((arm,i)=>arm.rotation.x=Math.sin(walkTime*13+i*Math.PI)*-.5);n.model.head.rotation.y=Math.sin(walkTime*2.1)*.16;}
for(let c of cheeses)if(c===n.targetCheese&&c.reservedBy===n&&!c.taken&&!c.relocating&&!n.flee&&!n.path.length&&Math.hypot(world(c.x)-p.x,world(c.z)-p.z)<.6){const danger=!travel&&dist<7&&lineClear(p,rat.position);if(danger){c.work=0;continue;}if(!c._working){c.work+=dt;c._working=true;}c.progress.visible=true;c.progress.scale.x=Math.max(.01,c.work/c.required);n.model.arms.forEach((arm,i)=>arm.rotation.x=-.8+Math.sin(walkTime*16+i)*.2);if(c.work>=c.required){c.taken=true;c.model.visible=false;releaseCheese(n);collected++;beep(180,.08);npcs.forEach(q=>{if(q.path.length>1)q.path=q.path.slice(0,1);});if(collected===8){gates.forEach(g=>g.bars.forEach(b=>b.visible=false));message('¡Abrieron las DOS salidas!');}else message(`Forzaron una jaula · ${collected}/8 quesos`);}}
if(collected>=8&&exits.some(e=>Math.hypot(p.x-world(e.x),p.z-world(e.z))<.65)){n.state='escaped';releaseCheese(n);n.model.visible=false;escaped++;message('Un explorador escapó');}}
for(let c of cheeses)if(!c.taken&&!c._working){c.work=0;c.progress.visible=false;}
if(elapsed>=300){npcs.filter(n=>n.state==='active').forEach(n=>{n.state='escaped';escaped++;});finish();}else if(caught+escaped===5)finish();hud();}
// Reservations keep each explorer focused on a different available cage.
function releaseCheese(n){const c=n.targetCheese;if(c&&c.reservedBy===n){c.reservedBy=null;c.work=0;c.progress.visible=false;}n.targetCheese=null;if(n.path.length>1)n.path=n.path.slice(0,1);}
function cheeseRoute(n,from){if(n.targetCheese){const c=n.targetCheese;if(!c.taken&&!c.relocating&&c.reservedBy===n)return path(from,c);releaseCheese(n);}let target=null,best=null;for(const c of cheeses){if(c.taken||c.relocating)continue;if(c.reservedBy&&(c.reservedBy.state!=='active'||c.reservedBy.flee||c.reservedBy.targetCheese!==c)){c.reservedBy=null;c.work=0;}if(c.reservedBy&&c.reservedBy!==n)continue;const route=path(from,c);if(!route.length&&(from.x!==c.x||from.z!==c.z))continue;if(!best||route.length<best.length){target=c;best=route;}}if(target){target.reservedBy=n;n.targetCheese=target;return best;}
// When every cage is assigned, keep moving away from occupied objectives.
let options=dirs.map(([dx,dz])=>({x:from.x+dx,z:from.z+dz})).filter(q=>cell(q.x,q.z));const busy=cheeses.filter(c=>!c.taken&&!c.relocating&&c.reservedBy);const score=q=>Math.min(20,...busy.map(c=>Math.abs(c.x-q.x)+Math.abs(c.z-q.z)))+(q.x===n.patrolPrevious?.x&&q.z===n.patrolPrevious?.z?-2:0);options.sort((a,b)=>score(b)-score(a));n.patrolPrevious=from;return options.length?[options[0]]:[];}
function senseRat(n,dt){const p=n.model.position,dx=rat.position.x-p.x,dz=rat.position.z-p.z,d=Math.hypot(dx,dz);const facing=(-Math.sin(n.model.rotation.y)*dx-Math.cos(n.model.rotation.y)*dz)/Math.max(.01,d);const sees=!travel&&d<14&&(d<2.8||facing>-.25)&&lineClear(p,rat.position);const was=n.flee;if(sees){n.alarm=3;n.lastThreat={x:tile(rat.position.x),z:tile(rat.position.z)};}else n.alarm=Math.max(0,(n.alarm||0)-dt);n.flee=n.alarm>0;if(n.flee&&!was){releaseCheese(n);n.wait=0;const center={x:tile(p.x),z:tile(p.z)};const offset=Math.hypot(world(center.x)-p.x,world(center.z)-p.z);n.path=offset>.05?[center]:[];n.model.head.rotation.y=0;}}
function fleeRoute(from,n){const threat=n.lastThreat||{x:tile(rat.position.x),z:tile(rat.position.z)};let options=dirs.map(([dx,dz])=>({x:from.x+dx,z:from.z+dz})).filter(c=>cell(c.x,c.z));let best=null,score=-Infinity;for(const next of options){let route=path(threat,next),distance=route.length;const branches=dirs.filter(([dx,dz])=>cell(next.x+dx,next.z+dz)).length;let s=distance+branches*.65;if(n.previousCell&&next.x===n.previousCell.x&&next.z===n.previousCell.z)s-=.3;if(s>score){score=s;best=next;}}n.previousCell=from;return best?[best]:[];}
function distanceField(origin){const d=new Map(),pending=[{...origin,cost:0}];d.set(key(origin.x,origin.z),0);while(pending.length){pending.sort((a,b)=>b.cost-a.cost);const p=pending.pop();if(p.cost!==d.get(key(p.x,p.z)))continue;const edges=dirs.map(([dx,dz])=>({x:p.x+dx,z:p.z+dz,cost:S})).filter(q=>cell(q.x,q.z));for(const t of tunnels)if(t.x===p.x&&t.z===p.z)edges.push({x:t.tx,z:t.tz,cost:1.4*4.5});for(const edge of edges){const k=key(edge.x,edge.z),cost=p.cost+edge.cost;if(cost<(d.get(k)??Infinity)){d.set(k,cost);pending.push({x:edge.x,z:edge.z,cost});}}}return d;}
function relocationSpot(c){const options=[];for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(cell(x,z)&&!(x===c.x&&z===c.z)&&!exits.some(e=>e.x===x&&e.z===z)&&!tunnels.some(t=>t.x===x&&t.z===z)&&!cheeses.some(q=>!q.taken&&q!==c&&(Math.abs(q.x-x)+Math.abs(q.z-z)<3||q.relocating?.target?.x===x&&q.relocating?.target?.z===z))){const distance=ratDistances.get(key(x,z))??0;if(Number.isFinite(distance))options.push({x,z,distance});}options.sort((a,b)=>b.distance-a.distance);const safe=options.filter(p=>p.distance>CAMP_RADIUS+S*2);return safe.length?safe[Math.floor(Math.random()*Math.min(8,safe.length))]:options[0];}
function beginRelocation(c){const target=relocationSpot(c);if(!target){c.camp=CAMP_WARN;return;}c.relocating={phase:'sink',time:0,target};if(c.reservedBy)releaseCheese(c.reservedBy);c.work=0;c.progress.visible=false;const hole=new T.Group();hole.position.set(world(c.x),.018,world(c.z));const disk=mesh(new T.CircleGeometry(1.0,28),new T.MeshBasicMaterial({color:0x020201,side:T.DoubleSide}),hole);disk.rotation.x=-Math.PI/2;const rim=mesh(new T.TorusGeometry(1.02,.055,5,28),material(0x6c4b21),hole,0,.01,0);rim.rotation.x=Math.PI/2;hole.scale.setScalar(.02);board.add(hole);c.hole=hole;message('Vigilaste demasiado: el suelo se traga el queso.');beep(80,.45);}
function updateCamping(dt){campScan-=dt;if(campScan<=0){campScan=.3;const source=travel?{x:travel.tx,z:travel.tz}:{x:tile(rat.position.x),z:tile(rat.position.z)};ratDistances=distanceField(source);}let warning=null;for(const c of cheeses){if(c.taken)continue;if(c.relocating){const r=c.relocating;r.time+=dt;if(r.phase==='sink'){const k=Math.min(1,r.time/1.25);c.hole.scale.setScalar(Math.min(1,k*3));c.model.position.y=-1.45*k*k;c.model.rotation.z=Math.sin(k*9)*.07;if(k===1){c.x=r.target.x;c.z=r.target.z;c.model.position.set(world(c.x),-1.4,world(c.z));c.model.rotation.z=0;c.hole.position.set(world(c.x),.018,world(c.z));r.phase='rise';r.time=0;}}else{const k=Math.min(1,r.time/.8);c.model.position.y=-1.4*(1-k);c.hole.scale.setScalar(Math.max(.01,1-k));if(k===1){board.remove(c.hole);c.hole.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});c.hole=null;c.relocating=null;c.camp=0;c.grace=3;c.model.position.y=0;}}continue;}c.grace=Math.max(0,c.grace-dt);if(c.grace>0)continue;const close=!travel&&(ratDistances.get(key(c.x,c.z))??Infinity)<=CAMP_RADIUS;c.camp=close?Math.min(CAMP_LIMIT,c.camp+dt):Math.max(0,c.camp-dt*.5);if(c.camp>=CAMP_LIMIT){beginRelocation(c);continue;}if(close&&c.camp>=CAMP_WARN&&(!warning||c.camp>warning.camp))warning=c;}$('campWarning').hidden=mode!=='playing'||!warning;if(warning)$('campWarning').textContent='DEJA DE VIGILAR EL QUESO · Se hunde en '+Math.ceil(CAMP_LIMIT-warning.camp)+' s';}
function escapeRoute(from){let best=[],bestScore=Infinity;for(let e of exits){const route=path(from,e);const ratDistance=Math.hypot(world(e.x)-rat.position.x,world(e.z)-rat.position.z);const risk=travel?0:Math.max(0,13-ratDistance)*12;const score=route.length+risk;if(score<bestScore){best=route;bestScore=score;}}return best;}
function nearbyTunnel(){return tunnels.find(t=>Math.hypot(world(t.x)-rat.position.x,world(t.z)-rat.position.z)<1.35);}
function enterTunnel(){if(mode!=='playing'||travel||tunnelCooldown>0)return;const entrance=nearbyTunnel();if(!entrance)return;travel={...entrance,time:0,duration:1.4};dashFor=0;message('Bajo las paredes…');beep(110,.3);}
function updateTunnel(dt){tunnelCooldown=Math.max(0,tunnelCooldown-dt);if(travel){travel.time+=dt;if(travel.time>=travel.duration){const destination=travel;rat.position.set(world(destination.tx),0,world(destination.tz));const opening=dirs.find(([dx,dz])=>cell(destination.tx+dx,destination.tz+dz));if(opening)yaw=Math.atan2(-opening[0],-opening[1]);pitch=0;travel=null;tunnelCooldown=2;message('Ya estás al otro lado.');}}}
function tunnelUI(){const near=mode==='playing'&&!travel?nearbyTunnel():null;$('tunnelUse').hidden=!near;$('tunnelUse').disabled=tunnelCooldown>0;$('tunnelUse').textContent=tunnelCooldown>0?'Recuperando el aliento…':near?'F · TÚNEL '+(near.pair+1)+' — Cruzar el laberinto':'';$('tunnelTravel').hidden=!travel||mode!=='playing';if(travel)$('tunnelTravel').textContent='BAJO EL QUESO · '+Math.round(travel.time/travel.duration*100)+'%';}
function lineClear(a,b){const steps=Math.ceil(a.distanceTo(b)*8);for(let i=1;i<steps;i++){const t=i/steps;if(!cell(tile(a.x+(b.x-a.x)*t),tile(a.z+(b.z-a.z)*t)))return false;}return true;}
function drawScent(){const visible=mode==='playing'&&!travel&&sniffFor>0;$('scentLayer').hidden=!visible;$('crosshair').hidden=mode!=='playing';$('lookHint').hidden=mode!=='playing'||document.pointerLockElement===$('world')||matchMedia('(pointer:coarse)').matches;document.body.classList.toggle('smelling',visible);for(let i=0;i<npcs.length;i++){let marker=$('scent'+i),n=npcs[i];marker.hidden=!visible||n.state!=='active';if(marker.hidden)continue;let dx=n.model.position.x-rat.position.x,dz=n.model.position.z-rat.position.z;let angle=Math.atan2(-dx,-dz)-yaw;angle=Math.atan2(Math.sin(angle),Math.cos(angle));const vec=n.model.position.clone();vec.y=1.3;vec.project(camera);const front=Math.abs(angle)<Math.PI/2;let onScreen=front&&Math.abs(vec.x)<.86&&Math.abs(vec.y)<.65;marker.style.left=(onScreen?(vec.x*.5+.5)*innerWidth:angle>0?innerWidth*.09:innerWidth*.91)+'px';marker.style.top=(onScreen?(-vec.y*.5+.5)*innerHeight:innerHeight*.48)+'px';marker.textContent=(onScreen?'◎ ':angle>0?'◀ ':'▶ ')+Math.round(Math.hypot(dx,dz))+' m';}}
function mapMarkers(){return {cheese:cheeses.filter(c=>!c.taken&&!c.relocating),npcs:sniffFor>0?npcs.filter(n=>n.state==='active'):[]};}
function drawMiniMap(){const active=mode==='playing';$('mapAbility').hidden=!active;$('miniMapPanel').hidden=!active||mapFor<=0;$('mapAbility').disabled=mapCD>0;$('mapAbility').classList.toggle('active',mapFor>0);$('mapAbility').textContent=mapFor>0?'INSTINTO · '+Math.ceil(mapFor)+' s':mapCD>0?'MAPA · '+Math.ceil(mapCD)+' s':'Q · INSTINTO';if(!active||mapFor<=0)return;$('mapRemaining').textContent=Math.ceil(mapFor)+' s';const canvas=$('miniMapCanvas'),ctx=canvas.getContext('2d'),size=canvas.width,u=size/N;ctx.fillStyle='#121810';ctx.fillRect(0,0,size,size);for(let z=0;z<N;z++)for(let x=0;x<N;x++){ctx.fillStyle=grid[z][x]?'#766b43':'#1e281b';ctx.fillRect(x*u+.6,z*u+.6,u-1.2,u-1.2);}const point=(x,z)=>[(x+.5)*u,(z+.5)*u];ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 19px Arial';for(const e of exits){const [x,y]=point(e.x,e.z);ctx.fillStyle=collected>=8?'#e8ab72':'#9d8263';ctx.fillRect(x-10,y-10,20,20);ctx.fillStyle='#160f08';ctx.fillText(e.name[0],x,y);}for(const t of tunnels){const [x,y]=point(t.x,t.z);ctx.fillStyle=['#8dc9d0','#b6a1df','#9bd594'][t.pair];ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0e1712';ctx.fillText(String(t.pair+1),x,y);}const markers=mapMarkers();ctx.fillStyle='#efd475';for(const c of markers.cheese){const [x,y]=point(c.x,c.z);ctx.beginPath();ctx.arc(x,y,4.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#f08a6f';for(const n of markers.npcs){const [x,y]=point(n.model.position.x/S+9,n.model.position.z/S+9);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();}const [px,py]=point(rat.position.x/S+9,rat.position.z/S+9);ctx.save();ctx.translate(px,py);ctx.rotate(-yaw);ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(9,10);ctx.lineTo(0,6);ctx.lineTo(-9,10);ctx.closePath();ctx.strokeStyle='#17130a';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#fff5d2';ctx.fill();ctx.restore();$('mapLegend').textContent='Flecha: tú · Dorado: queso · N/S: salidas · Números iguales: túneles'+(sniffFor>0?' · Rojo: NPC':'');}
function lockMouse(){if(!matchMedia('(pointer:coarse)').matches){try{const result=$('world').requestPointerLock?.();result?.catch(()=>{});}catch{}}}
function turn(dx,dy){yaw-=dx*.003;pitch=Math.max(-.8,Math.min(.8,pitch-dy*.0025));}
document.addEventListener('mousemove',e=>{if(mode==='playing'&&document.pointerLockElement===$('world'))turn(e.movementX,e.movementY);});
$('world').addEventListener('pointerdown',e=>{if(mode!=='playing')return;if(e.pointerType==='mouse'){lockMouse();}lookPointer=e.pointerId;lastLook={x:e.clientX,y:e.clientY};$('world').setPointerCapture?.(e.pointerId);});
$('world').addEventListener('pointermove',e=>{if(mode==='playing'&&lookPointer===e.pointerId&&document.pointerLockElement!==$('world')){turn(e.clientX-lastLook.x,e.clientY-lastLook.y);lastLook={x:e.clientX,y:e.clientY};}});
for(const event of ['pointerup','pointercancel'])$('world').addEventListener(event,()=>lookPointer=null);
function resize(){let w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
$('mapAbility').onclick=()=>ability('map');$('tunnelUse').onclick=enterTunnel;$('start').onclick=begin;$('restart').onclick=begin;$('pause').onclick=pause;$('resume').onclick=pause;$('sniff').onclick=()=>ability('sniff');$('dash').onclick=()=>ability('dash');$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'♫':'×';$('sound').setAttribute('aria-label',soundOn?'Silenciar sonido':'Activar sonido');};
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(e.repeat)return;if(k==='q'||k==='m')ability('map');if(k==='f')enterTunnel();if(k==='e')ability('sniff');if(k===' ')ability('dash');if(k==='escape'||k==='p')pause();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});
let joyId=null;function setJoy(e){let r=$('joystick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,z=e.clientY-r.top-r.height/2,d=Math.hypot(x,z),m=r.width*.34;if(d>m){x=x/d*m;z=z/d*m;}joy.x=x/m;joy.z=z/m;$('stick').style.transform=`translate(${x}px,${z}px)`;}
$('joystick').onpointerdown=e=>{if(joyId!==null)return;joyId=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);setJoy(e);};$('joystick').onpointermove=e=>{if(e.pointerId===joyId)setJoy(e);};function endJoy(){joyId=null;joy.x=joy.z=0;$('stick').style.transform='';}$('joystick').onpointerup=endJoy;$('joystick').onpointercancel=endJoy;
// A separate scene keeps the ending character clear of the maze and its walls.
const endScene=new T.Scene();endScene.background=new T.Color(0x100e0c);endScene.fog=new T.Fog(0x100e0c,9,22);
const endCamera=new T.PerspectiveCamera(43,1,.1,40);endScene.add(new T.HemisphereLight(0xe8d7bc,0x252326,2));
const rim=new T.DirectionalLight(0xe1a947,4);rim.position.set(3,5,1);endScene.add(rim);const fill=new T.DirectionalLight(0xb3c7cd,2);fill.position.set(-3,2,-5);endScene.add(fill);
const actor=makeRat();endScene.add(actor);const platform=mesh(new T.CylinderGeometry(2.1,2.3,.22,40),material(0x29291e),endScene,0,-.18,0);
const trophy=new T.Group();mesh(new T.CylinderGeometry(.45,.62,.6,3),mats.cheese,trophy,0,.5,0);trophy.position.set(-1.05,0,-.7);endScene.add(trophy);
const tearMaterial=new T.MeshStandardMaterial({color:0x9bdded,emissive:0x246171,roughness:.15});const tears=[-1,1].map(sign=>sphere(actor,tearMaterial,sign*.29,.84,-.96,.05,.12,.035));
function renderEnding(dt){endingTime+=dt;const t=endingTime;actor.position.y=won?Math.abs(Math.sin(t*3.5))*.45:Math.sin(t*1.8)*.015;actor.rotation.set(won?Math.sin(t*3.5)*.08:-.22,won?Math.sin(t*2.2)*.32:.14,won?Math.sin(t*3.5)*.12:Math.sin(t*1.7)*.025);actor.head.rotation.x=won?Math.sin(t*3.5)*.12:-.20;actor.ears.forEach((ear,i)=>ear.rotation.z=(i===0?1:-1)*(won?.22:.75));actor.paws.forEach((paw,i)=>{paw.position.y=won?.26+Math.sin(t*3.5+i)*.12:.20;});trophy.rotation.y=t*.7;tears.forEach((tear,i)=>{tear.position.y=.83-((t*.5+i*.25)%1)*.45;tear.scale.y=.09;});endCamera.aspect=innerWidth/innerHeight;endCamera.position.set(0,1.85,-5.6);endCamera.lookAt(innerWidth<650?0:1.05,innerWidth<650?-.85:.65,0);endCamera.updateProjectionMatrix();renderer.render(endScene,endCamera);}
$('playAgain').onclick=begin;
const tunnelScene=new T.Scene();tunnelScene.background=new T.Color(0x090c08);tunnelScene.fog=new T.Fog(0x090c08,2,17);const tunnelCamera=new T.PerspectiveCamera(85,1,.05,30);tunnelScene.add(new T.AmbientLight(0xa5aa82,1.6));const tube=mesh(new T.CylinderGeometry(1.5,1.5,30,16,1,true),new T.MeshStandardMaterial({color:0x383e2b,side:T.BackSide,roughness:1}),tunnelScene,0,0,-13);tube.rotation.x=Math.PI/2;const tunnelRings=[];for(let i=0;i<12;i++)tunnelRings.push(mesh(new T.TorusGeometry(1.43,.07,5,16),material(0x647250),tunnelScene,0,0,-i*2));
function renderTunnel(){tunnelCamera.aspect=innerWidth/innerHeight;tunnelCamera.updateProjectionMatrix();tunnelCamera.position.set(Math.sin(travel.time*18)*.035,Math.sin(travel.time*14)*.045,0);for(let i=0;i<tunnelRings.length;i++)tunnelRings[i].position.z=-24+((i*2+travel.time*19)%24);renderer.render(tunnelScene,tunnelCamera);}
reset();let last=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.04);last=now;if(mode==='playing')update(dt);toastFor-=dt;if(toastFor<=0)$('toast').style.opacity=0;camera.position.set(rat.position.x,.82+rat.position.y*.45,rat.position.z);camera.rotation.set(pitch,yaw,0,'YXZ');camera.updateMatrixWorld();drawScent();drawMiniMap();tunnelUI();hunterLight.position.copy(camera.position);hunterLight.intensity=13+Math.sin(now*.004)*.35;if(mode==='ended')renderEnding(dt);else if(travel)renderTunnel();else renderer.render(scene,camera);}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_hunt_status',description:'Read the current rat hunt score and remaining time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({status:mode,captured:caught,escaped,remainingSeconds:Math.max(0,Math.ceil(300-elapsed)),cheese:collected})})).catch(()=>{});}catch{}}
